using System.Collections.Generic;
using NUnit.Framework;
using RA2YR.Simulation;

namespace RA2YR.Tests.EditMode.Simulation
{
    public sealed class ProductionTechTests
    {
        private static ProductionReadLimits Limits(int diagnostics = 32) => new ProductionReadLimits(8, 8, 2, 4, diagnostics);
        private static ProductionDefinitionDescriptor Definition(long ordinal = 0, int tech = 2, long limit = 3) => new ProductionDefinitionDescriptor(new ProductionDefinitionRaw(ordinal, "Tank", "Vehicle", tech, 100, 10, limit, new[] { "WarFactory" }), "Synthetic");

        [Test] public void RawDefinitionPreservesPrerequisiteAndNumerics() { var d = Definition(); Assert.That(d.Raw.TypeRaw, Is.EqualTo("Tank")); Assert.That(d.Raw.PrerequisiteTokens[0], Is.EqualTo("WarFactory")); Assert.That(d.Raw.RawCost, Is.EqualTo(100)); }
        [Test] public void AvailabilityReportsAllExplicitBlockers() { var r = ProductionAvailabilityResult.Evaluate(new ProductionAvailabilityQuery(Definition(), 1, new string[0], 3, ProductionAvailabilityProfile.ExplicitCapabilitiesAndLimits), Limits()); Assert.That(r.IsVisible, Is.True); Assert.That(r.IsRequestable, Is.False); Assert.That(r.Blockers, Does.Contain("TechLevel")); Assert.That(r.Blockers, Does.Contain("BuildLimit")); }
        [Test] public void AvailabilitySucceedsOnlyWithExplicitCapabilitiesAndLimits() { var r = ProductionAvailabilityResult.Evaluate(new ProductionAvailabilityQuery(Definition(), 2, new[] { "WarFactory" }, 0, ProductionAvailabilityProfile.ExplicitCapabilitiesAndLimits), Limits()); Assert.That(r.IsSuccess, Is.True); Assert.That(r.IsRequestable, Is.True); }
        [Test] public void InvalidAvailabilityPolicyFailsBeforeCapabilityEnumeration() { var consumed = false; System.Collections.Generic.IEnumerable<string> Explosive() { consumed = true; yield return "boom"; } var r = ProductionAvailabilityResult.Evaluate(new ProductionAvailabilityQuery(Definition(), 2, Explosive(), 0, (ProductionAvailabilityProfile)99), Limits()); Assert.That(r.IsSuccess, Is.False); Assert.That(consumed, Is.False); }
        [Test] public void NegativeBuildLimitRemainsUnboundedCandidate() { var r = ProductionAvailabilityResult.Evaluate(new ProductionAvailabilityQuery(Definition(limit: -1), 2, new[] { "WarFactory" }, 999, ProductionAvailabilityProfile.ExplicitCapabilitiesAndLimits), Limits()); Assert.That(r.IsRequestable, Is.True); }
        [Test] public void QueueEnqueuePreservesStableFifoOrder() { var q = new ProductionQueue(Limits()); IReadOnlyList<ProductionDiagnostic> d; Assert.That(q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 1), out d), Is.True); Assert.That(q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(2), new PlayerId(0), "B", "Vehicle", 10, 5, 0), out d), Is.True); Assert.That(q.Entries[0].TypeRaw, Is.EqualTo("B")); }
        [Test] public void DuplicateQueueIdFailsClosed() { var q = new ProductionQueue(Limits()); IReadOnlyList<ProductionDiagnostic> d; q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 0), out d); Assert.That(q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "B", "Vehicle", 10, 5, 1), out d), Is.False); Assert.That(d[0].Code, Is.EqualTo(ProductionDiagnosticCode.DuplicateQueueId)); }
        [Test] public void QueueBudgetFailsBeforeAppending() { var q = new ProductionQueue(new ProductionReadLimits(8, 8, 2, 0, 32)); IReadOnlyList<ProductionDiagnostic> d; Assert.That(q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 0), out d), Is.False); Assert.That(q.Entries.Count, Is.EqualTo(0)); }
        [Test] public void QueueProgressIsCheckedAndExact() { var q = new ProductionQueue(Limits()); IReadOnlyList<ProductionDiagnostic> d; q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 0), out d); ProductionQueueEntry updated; Assert.That(q.TryAdvance(new ProductionQueueId(1), 3, out updated, out d), Is.True); Assert.That(updated.Progress, Is.EqualTo(3)); Assert.That(q.TryAdvance(new ProductionQueueId(1), 9, out updated, out d), Is.True); Assert.That(updated.Progress, Is.EqualTo(5)); Assert.That(updated.IsComplete, Is.True); }
        [Test] public void InvalidProgressDoesNotMutateQueue() { var q = new ProductionQueue(Limits()); IReadOnlyList<ProductionDiagnostic> d; q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 0), out d); ProductionQueueEntry updated; Assert.That(q.TryAdvance(new ProductionQueueId(1), 0, out updated, out d), Is.False); Assert.That(q.Entries[0].Progress, Is.EqualTo(0)); }
        [Test] public void ZeroDiagnosticBudgetStillFailsDuplicate() { var q = new ProductionQueue(new ProductionReadLimits(8, 8, 2, 4, 0)); IReadOnlyList<ProductionDiagnostic> d; q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 0), out d); Assert.That(q.TryEnqueue(new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "B", "Vehicle", 10, 5, 1), out d), Is.False); }
        [Test] public void CanonicalQueueHashIgnoresInsertionOrderWhenOrdinalStable() { var a = new ProductionQueue(Limits()); var b = new ProductionQueue(Limits()); IReadOnlyList<ProductionDiagnostic> d; var one = new ProductionQueueEntry(new ProductionQueueId(1), new PlayerId(0), "A", "Vehicle", 10, 5, 1); var two = new ProductionQueueEntry(new ProductionQueueId(2), new PlayerId(0), "B", "Vehicle", 10, 5, 0); a.TryEnqueue(one, out d); a.TryEnqueue(two, out d); b.TryEnqueue(two, out d); b.TryEnqueue(one, out d); Assert.That(a.CanonicalHash(), Is.EqualTo(b.CanonicalHash())); }
        [Test] public void CoreProductionAssemblyHasNoUnityReferences() { Assert.That(typeof(ProductionQueue).Assembly.GetReferencedAssemblies(), Has.None.Matches<System.Reflection.AssemblyName>(x => x.Name == "UnityEngine" || x.Name == "UnityEditor")); }
    }
}
